FROM almalinux:8
# docker images --filter "label=mylabel=value
LABEL TRAINING="DEVOPS" \     
      TRAINER="Hitesh" \
      DURATION="120HRS" \
      org.opencontainers.image.authors="hithesh@joindevops.com"